import { RwaAsset } from "./types";

export const initialAssets: RwaAsset[] = [
  {
    id: 1,
    title: "The Grand Horizon Villa",
    type: "House",
    price: "0.015",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    owner: "0x32A46fc7d9382fCe5De1C203649E8284C228E47b",
    location: "Malibu, California",
    specs: "4,500 sqft / 5 Bed / Yield: 8.4%",
    description: "A breathtaking architectural masterpiece nestled cliffside with panoramic Pacific Ocean views. Features solar smart automation, an outdoor infinity pool, private beach access, and premium travertine marble finishes throughout.",
    yieldApr: 8.4,
    isDefault: true
  },
  {
    id: 2,
    title: "Cyber GT Concept-X",
    type: "Car",
    price: "0.008",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    owner: "Velocity Premium Labs",
    location: "Munich Vault B-4",
    specs: "Electric / 850 HP / 0-60 in 1.9s",
    description: "Next-generation carbon-fiber electric hypercar concept. Fully registered real-world high-performance asset with fractional storage insurance, carbon tracking ledger, and tokenized utility membership.",
    yieldApr: 9.1,
    isDefault: true
  },
  {
    id: 3,
    title: "Metropolitan Sky Penthouse",
    type: "House",
    price: "0.022",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    owner: "0xF21a228BC228E47b32A46fc7d9382fCe5De1C203",
    location: "Manhattan, New York",
    specs: "3,100 sqft / Duplex / Yield: 7.1%",
    description: "Luxury duplex penthouse overlooking Central Park. Floored with Calacatta marble, 14-foot floor-to-ceiling glass walls, private direct-elevator access, double wine-cellar integration, and dual dynamic outdoor terraces.",
    yieldApr: 7.1,
    isDefault: true
  },
  {
    id: 4,
    title: "Vanguard Overland SUV",
    type: "Car",
    price: "0.005",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    owner: "0x77c2298ef9ef9ef032d93F642f64180aa3f6ee1a",
    location: "Aspen Asset Storage",
    specs: "EV SUV / 4x4 / Off-grid Pack",
    description: "Rugged heavy-duty electric exploration vehicle. Ready for off-grid adventure with rooftop solar generation, integrated vehicle vehicle-to-home battery backup, extreme cold-temperature chassis heating, and auto-terrain leveling.",
    yieldApr: 6.5,
    isDefault: true
  },
  {
    id: 5,
    title: "Alpine Sanctuary Chalet",
    type: "House",
    price: "0.018",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    owner: "Aspen Alpine Trust",
    location: "Zermatt, Switzerland",
    specs: "2,800 sqft / ski-in-out / Yield: 9.2%",
    description: "An ultra-cozy luxury mountain sanctuary built from reclaimed historical larchwood and local granite. Offers prime ski-in/ski-out privileges directly onto the Cervino slopes, private thermal hot springs tub, and wine cellar.",
    yieldApr: 9.2,
    isDefault: true
  },
  {
    id: 6,
    title: "Apex Roadster S",
    type: "Car",
    price: "0.012",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    owner: "0x2B98E12E47b32A46fc7d9382fCe5De1C2036A89CC",
    location: "London Vault C-1",
    specs: "V8 Twin-Turbo / 720 HP / Classic Manual",
    description: "Carbon red track-focused performance roadster with manual gated gearbox, active titanium aerodynamics, and carbon-ceramic braking array. Certified investment-grade limited-production model.",
    yieldApr: 8.0,
    isDefault: true
  },
  {
    id: 7,
    title: "Elysian Estate Vineyards",
    type: "House",
    price: "0.045",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    owner: "0x91FA9382fCe5De1C203649E8284C228E47b32A46",
    location: "Tuscany, Italy",
    specs: "8,900 sqft / Vineyard / Yield: 11.5%",
    description: "Sprawling historical vineyard estate in the heart of Chianti. Includes 15th-century luxury master villa, modern olive oil and wine production facility, storage cells, and high commercial yield contracts for ongoing revenue.",
    yieldApr: 11.5,
    isDefault: true
  },
  {
    id: 8,
    title: "Monaco Azure Yacht Share",
    type: "Other",
    price: "0.035",
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=800&q=80",
    owner: "Lady Victoria Pembroke",
    location: "Port Hercule, Monaco",
    specs: "110ft Custom Cruiser / Yield: 6.8%",
    description: "Fractional equity share in a pristine bespoke 110ft luxury cruiser. Fully crewed, with professional summer/winter charter booking management yielding predictable off-season revenue directly to token holders.",
    yieldApr: 6.8,
    isDefault: true
  },
  {
    id: 9,
    title: "The Emerald Solis Villa",
    type: "House",
    price: "0.028",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80",
    owner: "Ibiza Premium Holdings",
    location: "Ibiza, Spain",
    specs: "5,200 sqft / 6 Bed / Infinity Pool",
    description: "Bespoke contemporary villa on the hills of Ibiza. Features floor-to-ceiling sliding glass walls, panoramic sunset vistas over the Balearic Sea, smart bio-climatic climate control, and solid travertine flooring.",
    yieldApr: 9.5,
    isDefault: true
  },
  {
    id: 10,
    title: "Nebula GTR Hypercar",
    type: "Car",
    price: "0.016",
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80",
    owner: "Zenith Automotive Labs",
    location: "Tokyo Vault A-9",
    specs: "Quad-Motor EV / 1200 HP / 0-60 in 1.6s",
    description: "Stunning track-engineered electric hypercar featuring advanced computational torque vectoring, monolithic carbon-epoxy composite shell, active plasma kinetic aerodynamics, and secured Lloyd's shipping insurance.",
    yieldApr: 10.2,
    isDefault: true
  },
  {
    id: 11,
    title: "The Obsidian Chalet",
    type: "House",
    price: "0.034",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    owner: "0xAspenChaletTrust",
    location: "Aspen, Colorado",
    specs: "4,100 sqft / Ski-in ski-out / Heated pool",
    description: "Ultra-private winter compound with ski-out access. Finished with dark slate stone, high cedar beams, double thermal insulation, automated heli-pad, heated indoor lap pool, and a private wine cave.",
    yieldApr: 8.7,
    isDefault: true
  },
  {
    id: 12,
    title: "Bespoke Patek Philippe Nautilus",
    type: "Other",
    price: "0.009",
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=80",
    owner: "Geneva Vaulting Group",
    location: "Geneva Vault C-12",
    specs: "Ref. 5711/1A-010 / Steel / Blue Dial",
    description: "Coveted collector luxury watch under heavy vault protection. Insured against all physical damages with a certified ledger deed, accompanied by full authentic packaging, provenance records, and micro-ownership certs.",
    yieldApr: 7.2,
    isDefault: true
  },
  {
    id: 13,
    title: "Aetheria Superyacht Share",
    type: "Other",
    price: "0.042",
    image: "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=800&q=80",
    owner: "Lady Cynthia Sterling",
    location: "Amalfi Coast, Italy",
    specs: "130ft Custom Hull / Sleeps 12 / Crewed",
    description: "Continuous yield fractional share in a bespoke yacht cruiser. Managed by elite charter firms with premium Mediterranean summer and winter bookings, generating high dividend flows directly to share owners.",
    yieldApr: 11.0,
    isDefault: true
  },
  {
    id: 14,
    title: "The Ivory Sand Estate",
    type: "House",
    price: "0.031",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    owner: "Cycladic Trust Fund",
    location: "Mykonos, Greece",
    specs: "6,400 sqft / Beachfront / Heli-pad",
    description: "Immaculate whitewashed Cycladic architectural estate situated directly beachfront. Features an extensive multi-level saltwater lagoon infinity pool, private deep-water boat dock, and high rental yield seasonal leases.",
    yieldApr: 9.8,
    isDefault: true
  },
  {
    id: 15,
    title: "Monarch Vintage Roadster",
    type: "Car",
    price: "0.014",
    image: "https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=800&q=80",
    owner: "0xMilanHeritageAuto",
    location: "Milan Safe Storage",
    specs: "1964 V12 Roadster / Original Chassis",
    description: "Immaculate investment-grade vintage masterpiece. Hand-restored matching-numbers sports coupe with full original leather interior, certified historical verification, and continuous museum rental dividends.",
    yieldApr: 7.5,
    isDefault: true
  },
  {
    id: 16,
    title: "Stellar Horizon Penthouse",
    type: "House",
    price: "0.026",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    owner: "0xDubaiLegacyInvest",
    location: "Dubai Marina, UAE",
    specs: "3,800 sqft / Duplex / 360 Sky Deck",
    description: "Stellar duplex penthouse suspended above the Dubai Marina skyline. Offers a private high-altitude glass plunge pool, personal executive office suite, triple-reinforced soundproofing, and integrated SmartHome security.",
    yieldApr: 8.1,
    isDefault: true
  },
  {
    id: 17,
    title: "Rare Blue Diamond Ring",
    type: "Other",
    price: "0.019",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    owner: "Hatton Diamond Custodian",
    location: "London Hatton Vault",
    specs: "3.2 Carat Fancy Blue / VS1 Cert",
    description: "An exceptional GIA-certified fancy intense blue oval diamond set in platinum. Held in deep secure vaults under sovereign bank trust frameworks, insured for full retail replacement valuation.",
    yieldApr: 6.4,
    isDefault: true
  },
  {
    id: 18,
    title: "The Whisperwood Retreat",
    type: "House",
    price: "0.021",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80",
    owner: "Kyoto Heritage Trust",
    location: "Kyoto, Japan",
    specs: "2,500 sqft / Zen Garden / Hot Spring",
    description: "An authentic, painstakingly preserved wooden machiya estate featuring a flowing thermal spring onsen bath, tranquil dry-gravel Zen gardens, sliding shoji panel doors, and stable cultural tourism leasing dividends.",
    yieldApr: 7.9,
    isDefault: true
  },
  {
    id: 19,
    title: "Tempest Track Hypercar",
    type: "Car",
    price: "0.013",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    owner: "Silverstone Track Club",
    location: "Silverstone Vault C-5",
    specs: "Naturally Aspirated V10 / 750 HP",
    description: "A track-only carbon-clad purebred roadster. Features a screaming F1-derived V10 engine, active aerodynamic underbody venturi channels, and locked track-day rental operations yielding consistent passive revenue streams.",
    yieldApr: 8.8,
    isDefault: true
  },
  {
    id: 20,
    title: "The Azure Coast Villa",
    type: "House",
    price: "0.038",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    owner: "Riviera Blue Chip Fund",
    location: "Saint-Tropez, France",
    specs: "5,800 sqft / Private Dock / Vineyard",
    description: "Spectacular oceanfront villa on the Saint-Tropez coastline. Features a deep-water dock for yachts up to 80ft, dynamic solar-harvesting architectural wings, a micro-vineyard, and premium French country limestone finishes.",
    yieldApr: 9.4,
    isDefault: true
  },
  {
    id: 21,
    title: "Apollo Lunar Watch Chrono",
    type: "Other",
    price: "0.007",
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80",
    owner: "Space Heritage Archival",
    location: "Houston Safe Box",
    specs: "Flown Astronaut Lunar-Mod Edition",
    description: "A highly rare historical chronograph timepiece flown on active Apollo lunar surface missions. Insured and preserved in an inert nitrogen security cell with complete flight log books and NASA provenance certificates.",
    yieldApr: 6.9,
    isDefault: true
  },
  {
    id: 22,
    title: "The Alabaster Manor",
    type: "House",
    price: "0.029",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    owner: "Cotswold Heritage Estates",
    location: "Cotswolds, England",
    specs: "7,200 sqft / Private Lake / Historic",
    description: "An authentic 18th-century English manor house constructed of premium Cotswolds honey stone. Beautifully modernized internally, incorporating a private trout lake, equestrian stables, and smart climate control.",
    yieldApr: 8.3,
    isDefault: true
  },
  {
    id: 23,
    title: "Horizon GT Grand Tourer",
    type: "Car",
    price: "0.011",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    owner: "0xStuttgartVelocityGroup",
    location: "Stuttgart Storage",
    specs: "Twin-Turbo V6 / 620 HP / Luxury Cabin",
    description: "High-end bespoke grand touring supercar. Equipped with adaptive active active-suspension, premium hand-stitched aniline leather cabin, active noise-canceling shell, and high corporate leasing demand yields.",
    yieldApr: 7.0,
    isDefault: true
  },
  {
    id: 24,
    title: "Bespoke Hermès Birkin 35",
    type: "Other",
    price: "0.004",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    owner: "Hermes Archival Syndicate",
    location: "Paris Security Locker",
    specs: "Matte Niloticus Crocodile / Palladium",
    description: "An ultra-exclusive matte Niloticus crocodile leather bag with palladium clasp hardware. Placed under pristine temperature-controlled museum storage and backed by historical capital appreciation indexes.",
    yieldApr: 5.8,
    isDefault: true
  },
  {
    id: 25,
    title: "The Saffron Sands Estate",
    type: "House",
    price: "0.023",
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    owner: "0xMarrakechRiadHoldings",
    location: "Marrakech, Morocco",
    specs: "4,900 sqft / Private Riad / Pool",
    description: "A beautifully restored traditional high-luxury riad featuring intricate hand-carved cedarwood gates, a cooling mosaic central courtyard pool, heated hammam, and lucrative luxury vacation lease yield profiles.",
    yieldApr: 8.6,
    isDefault: true
  },
  {
    id: 26,
    title: "Chrono Marine Speedboat",
    type: "Other",
    price: "0.017",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
    owner: "0xMiamiYachtRentals",
    location: "Miami Marina B-12",
    specs: "42ft Custom Powerboat / Twin 450HP",
    description: "High-performance luxury custom powerboat built with advanced composites. Features carbon trim cockpit, twin racing engines, active gyro stabilizers, and high demand weekend charter yields in Miami beach.",
    yieldApr: 9.0,
    isDefault: true
  },
  {
    id: 27,
    title: "Vanguard Electric Roadster",
    type: "Car",
    price: "0.015",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    owner: "0xSiliconValleyTeslaTrust",
    location: "Silicon Valley Vault",
    specs: "Monolithic Carbon / Autopilot / 900 HP",
    description: "Next-gen solid-state battery electric roadster with quad-motor digital torque vectoring, biometric cabin entry, and legal securitized trust fraction titles returning high commercial promo charter yields.",
    yieldApr: 8.2,
    isDefault: true
  },
  {
    id: 28,
    title: "Ancient Roman Gold Coin Set",
    type: "Other",
    price: "0.010",
    image: "https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&w=800&q=80",
    owner: "Vatican Coin Archivists",
    location: "Rome Archival Vault",
    specs: "Julius Caesar Denarius Set / NGC Cert",
    description: "A flawless set of authentic gold Aurei coins from the late Roman Republic. NGC authenticated and graded under sovereign banking trust custody, insured, and generating passive research display lease yields.",
    yieldApr: 7.4,
    isDefault: true
  },
  {
    id: 29,
    title: "Serenity Shores Island Share",
    type: "Other",
    price: "0.040",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    owner: "Island Holdings LLC",
    location: "Maldives Private Atoll",
    specs: "Overwater Bungalow / Eco-Solar Pack",
    description: "Fractional equity in a luxury private island resort in the Maldives. Offers a robust rental dividend pool, fully managed, insured, with dual-tier passive high seasonal yield distribution.",
    yieldApr: 9.5,
    isDefault: true
  },
  {
    id: 30,
    title: "Neon Stealth Hypercar",
    type: "Car",
    price: "0.015",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80",
    owner: "Tokyo Velocity Club",
    location: "Tokyo Vault B-2",
    specs: "Twin Turbo V8 / Hybrid / 1000 HP",
    description: "A state-of-the-art hybrid hypercar featuring active aerodynamics and real-time telemetry tracking. Yield is backed by high-end film production charters and museum display agreements.",
    yieldApr: 8.8,
    isDefault: true
  },
  {
    id: 31,
    title: "Elysian Sky Duplex",
    type: "House",
    price: "0.025",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    owner: "0x8922C0A46fc7d9382fCe5De1C203649E8284C228",
    location: "Singapore Sky-Heights",
    specs: "3,800 sqft / Dual Pool / Sky View",
    description: "High-yield premium duplex in Singapore. Fully tenanted with long-term high-net-worth commercial leases. Offers stable quarterly yield distributions under local legal asset-backed trusts.",
    yieldApr: 7.6,
    isDefault: true
  },
  {
    id: 32,
    title: "Royal Imperial Crown Sapphire",
    type: "Other",
    price: "0.011",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    owner: "Zurich Archival Safe",
    location: "Geneva, Switzerland",
    specs: "42 Carats / Royal Blue / GIA Certified",
    description: "A museum-grade natural Royal Blue Sapphire of historic value. Fully authenticated, stored in climate-controlled security vaults, and generating exhibition display lease yields.",
    yieldApr: 6.2,
    isDefault: true
  },
  {
    id: 33,
    title: "Monarch Redwood Estate",
    type: "House",
    price: "0.019",
    image: "https://images.unsplash.com/photo-1508333706533-1ab43ecb1606?auto=format&fit=crop&w=800&q=80",
    owner: "Napa Valley Trust",
    location: "Napa Valley, California",
    specs: "5,200 sqft / Vineyard Access / Off-grid",
    description: "A stunning, architectural estate surrounded by ancient Redwoods and pristine vineyards. Features dynamic solar arrays and smart off-grid backup with premium commercial rental returns.",
    yieldApr: 8.5,
    isDefault: true
  },
  {
    id: 34,
    title: "Formula-X Track Prototype",
    type: "Car",
    price: "0.014",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    owner: "Formula Syndicate Group",
    location: "Silverstone Storage",
    specs: "10,000 RPM / Formula Config / V6 Hybrid",
    description: "Track-only extreme high-performance hypercar. Yield is generated via exclusive racing simulator licensing rights and premium club track day rentals overseen by professional crews.",
    yieldApr: 9.0,
    isDefault: true
  },
  {
    id: 35,
    title: "L'Horizon Azure Oceanfront Mansion",
    type: "House",
    price: "0.038",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    owner: "Saint-Tropez Luxury Trust",
    location: "Saint-Tropez, France",
    specs: "6,400 sqft / Cliffside / Smart Home",
    description: "A magnificent Mediterranean villa on the edge of Saint-Tropez. Boasts high seasonal luxury retreat revenues with real-time smart locks and biometric guest check-in integrations.",
    yieldApr: 10.2,
    isDefault: true
  },
  {
    id: 36,
    title: "1963 Classic Luxury Cruiser",
    type: "Car",
    price: "0.009",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80",
    owner: "Monterey Classic Garage",
    location: "Monterey Vault A-1",
    specs: "V8 Classic / Concours Gold Medallist",
    description: "An iconic, fully restored luxury cruiser in pristine mechanical condition. Revenue is accumulated through commercial film leases and high-tier luxury concours exhibitions.",
    yieldApr: 7.5,
    isDefault: true
  },
  {
    id: 37,
    title: "Galactic Explorer Watch Collection",
    type: "Other",
    price: "0.007",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    owner: "Geneva Safe Room",
    location: "Geneva, Switzerland",
    specs: "Platinum / Triple-Axis Tourbillon",
    description: "A legendary watch series crafted by Swiss master horologists. Features stellar chronographic movement, carbon space-alloy casing, and generates rental yields on high-end fashion shoots.",
    yieldApr: 6.8,
    isDefault: true
  },
  {
    id: 38,
    title: "Northern Lights Glass Cabin",
    type: "House",
    price: "0.012",
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&w=800&q=80",
    owner: "Arctic Sanctuary Group",
    location: "Tromsø, Norway",
    specs: "1,200 sqft / Heated Glass Roof",
    description: "A luxury architectural cabin in northern Norway designed for aurora viewing. Fully managed with booking revenues streamed directly into the SPV's dividend wallet.",
    yieldApr: 8.1,
    isDefault: true
  },
  {
    id: 39,
    title: "Titan GT Quad-Motor Truck",
    type: "Car",
    price: "0.006",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
    owner: "Texas Overland Base",
    location: "Austin Storage Vault",
    specs: "Quad-Motor EV / 1,200 HP / Off-grid Pack",
    description: "Supercharged heavy-duty electric truck. Yield is generated through commercial solar vehicle and off-grid generator power leases under state-wide public utility agreements.",
    yieldApr: 7.0,
    isDefault: true
  },
  {
    id: 40,
    title: "Emerald Legacy Diamond Necklace",
    type: "Other",
    price: "0.013",
    image: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=800&q=80",
    owner: "London Security Vault",
    location: "London, United Kingdom",
    specs: "28 Carats Emeralds / 18k White Gold",
    description: "A highly prestigious, historical design emerald necklace under secure institutional custody. Insured by Lloyd's, producing display dividends on high-profile global exhibitions.",
    yieldApr: 6.4,
    isDefault: true
  },
  {
    id: 41,
    title: "Grand Imperial Castle Estate",
    type: "House",
    price: "0.042",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    owner: "Bavarian Heritage Trust",
    location: "Bavaria, Germany",
    specs: "15,000 sqft / Restored Moat / Solar-Fit",
    description: "A historic castle estate renovated into a carbon-neutral premium hospitality center. High-tier weddings and executive retreats fuel steady, high-performing annual yields.",
    yieldApr: 9.8,
    isDefault: true
  },
  {
    id: 42,
    title: "Ghost-Rider Custom Chopper",
    type: "Car",
    price: "0.004",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
    owner: "Vegas Performance Depot",
    location: "Las Vegas Warehouse",
    specs: "Custom Titanium Frame / 130ci Motor",
    description: "A fully custom-built masterpiece of custom motorcycle design. Insured, stored in Nevada, and returning regular display rental yields in high-profile vehicle exhibitions.",
    yieldApr: 8.2,
    isDefault: true
  },
  {
    id: 43,
    title: "Vintage Tuscan Vineyard Estate",
    type: "House",
    price: "0.026",
    image: "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=800&q=80",
    owner: "Tuscan Hills Asset Co.",
    location: "Siena, Italy",
    specs: "4,200 sqft / Active Olive Grove",
    description: "A beautifully restored stone villa with surrounding olive groves and vineyards. Yield is derived from premium organic product sales and luxury agritourism leases.",
    yieldApr: 9.0,
    isDefault: true
  },
  {
    id: 44,
    title: "Ancient Greek Gold Solidus Coin",
    type: "Other",
    price: "0.005",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    owner: "Athens Archival Vault",
    location: "Athens, Greece",
    specs: "24k Pure Gold / Byzantine Era / Gem Mint",
    description: "A flawless, highly rare gold Solidus from the Byzantine Golden Age. Fully registered and cataloged, producing steady research display lease yields.",
    yieldApr: 5.5,
    isDefault: true
  },
  {
    id: 45,
    title: "Sunset Cliffs Glass Pavilion",
    type: "House",
    price: "0.029",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80",
    owner: "Big Sur Coastal Trust",
    location: "Big Sur, California",
    specs: "3,500 sqft / Cantilevered Deck",
    description: "An architectural marvel overlooking the Pacific Ocean. Operates as an elite film set and high-end celebrity holiday retreat, delivering excellent annual rent yields.",
    yieldApr: 8.7,
    isDefault: true
  },
  {
    id: 46,
    title: "Aero-Sprint Custom Biplane",
    type: "Other",
    price: "0.010",
    image: "https://images.unsplash.com/photo-1483450388369-9ed95738483c?auto=format&fit=crop&w=800&q=80",
    owner: "Aero-Reserve Storage",
    location: "Aspen Airport Hangar",
    specs: "Supercharged Radial Engine / Classic Rig",
    description: "A meticulously maintained modern reproduction of a classic radial-engine biplane. Fully licensed and certified for exhibition flights and cinematic charters.",
    yieldApr: 7.9,
    isDefault: true
  },
  {
    id: 47,
    title: "Stardust Carbon Hyperbike",
    type: "Car",
    price: "0.003",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80",
    owner: "Bologna Racing Labs",
    location: "Bologna, Italy",
    specs: "Carbon Monocoque / Dual EV Drive",
    description: "A zero-emission electric hyperbike. Fully track-tested with integrated smart blockchain diagnostics, yielding returns through technical track leasing programs.",
    yieldApr: 9.3,
    isDefault: true
  },
  {
    id: 48,
    title: "Royal Palace Kyoto Penthouse",
    type: "House",
    price: "0.021",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    owner: "Kyoto Estate Partners",
    location: "Kyoto, Japan",
    specs: "2,900 sqft / Cypress Bath / Garden",
    description: "An authentic, luxury penthouse adjacent to the Kyoto Imperial Palace gardens. Delivers steady rental returns from premium corporate executive leases.",
    yieldApr: 7.8,
    isDefault: true
  },
  {
    id: 49,
    title: "Nouveau Art Glass Chandelier",
    type: "Other",
    price: "0.008",
    image: "https://images.unsplash.com/photo-1540931900642-1be96af3bf6a?auto=format&fit=crop&w=800&q=80",
    owner: "Paris Design Archives",
    location: "Paris, France",
    specs: "Hand-Blown Murano / 120-Light Array",
    description: "An exquisite Murano hand-blown glass masterpiece from the early 20th century. High museum exhibition demand ensures predictable, recurring display lease dividends.",
    yieldApr: 6.0,
    isDefault: true
  },
  {
    id: 50,
    title: "Vanderbilt Classic Sedan",
    type: "Car",
    price: "0.007",
    image: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=800&q=80",
    owner: "Detroit Classic Vault",
    location: "Detroit, Michigan",
    specs: "V12 Flathead / 1934 Roadster Config",
    description: "An award-winning vintage sedan from the golden era of American design. Generates recurring dividend streams through advertising, television, and film licensing deals.",
    yieldApr: 7.2,
    isDefault: true
  },
  {
    id: 51,
    title: "Oasis Desert Eco-Villa",
    type: "House",
    price: "0.023",
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=80",
    owner: "Dubai Desert Reserves",
    location: "Dubai, United Arab Emirates",
    specs: "4,000 sqft / Solar-Water / Dune View",
    description: "A stunning luxury villa built using advanced sustainable desert architecture. Yield is backed by high-tier eco-tourism bookings and carbon offsetting credit syndicates.",
    yieldApr: 9.4,
    isDefault: true
  },
  {
    id: 52,
    title: "Celestial Meteorite Specimen",
    type: "Other",
    price: "0.015",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    owner: "Smithsonian Safe Room",
    location: "Washington, D.C.",
    specs: "Iron-Nickel Pallasite / 85 kg / Certified",
    description: "A spectacular olivine-rich space pallasite meteorite. Under complete security vault custody, returning high-value lease payouts from academic research and private exhibitions.",
    yieldApr: 7.1,
    isDefault: true
  },
  {
    id: 53,
    title: "Aero-Stream Luxury Land-Yacht",
    type: "Car",
    price: "0.008",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    owner: "Phoenix Storage Group",
    location: "Phoenix, Arizona",
    specs: "Twin EV Motors / Auton / 40ft Lounge",
    description: "A custom 40-foot electric land-yacht with extreme premium interior design. Fully equipped for VIP transit and mobile business lounge leases, producing robust returns.",
    yieldApr: 8.0,
    isDefault: true
  },
  {
    id: 54,
    title: "Historical Wine Barrique Cellar",
    type: "Other",
    price: "0.014",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
    owner: "Bordeaux Estate Partners",
    location: "Bordeaux, France",
    specs: "10-Barrique Lot / Grand Cru / 1996",
    description: "A highly prestigious Grand Cru wine cellar lot. Yield is actively accumulated from institutional wine futures trade and high-end restaurant bulk procurement rights.",
    yieldApr: 10.5,
    isDefault: true
  },
  {
    id: 55,
    title: "Vanguard Sky-Lodge Cabin",
    type: "House",
    price: "0.016",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80",
    owner: "Whistler Alpine Trust",
    location: "Whistler, Canada",
    specs: "2,500 sqft / Hot Spring Pool / Modern",
    description: "A cozy modern lodge nestled in the peak forests of Whistler. Generates reliable winter-sports and summer-hiking rentals through automated property management contracts.",
    yieldApr: 8.3,
    isDefault: true
  },
  {
    id: 56,
    title: "Stealth Falcon Custom Jet-Share",
    type: "Other",
    price: "0.033",
    image: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=800&q=80",
    owner: "Munich Jet Center",
    location: "Munich, Germany",
    specs: "8-Passenger / Mach 0.8 / Smart Cabin",
    description: "Securitized fractional ownership in a premium long-range private business jet. High corporate subscription booking revenues provide steady monthly cashflow distributions.",
    yieldApr: 9.1,
    isDefault: true
  },
  {
    id: 57,
    title: "Monza Track Hybrid Hypercar",
    type: "Car",
    price: "0.017",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    owner: "Monza Special Depot",
    location: "Monza, Italy",
    specs: "Quad-Turbo Hybrid / KERS / 1050 HP",
    description: "A track-optimized hybrid hypercar featuring formula-grade KERS power recovery. Revenue is driven by premium testing events and display lease licensing.",
    yieldApr: 8.9,
    isDefault: true
  },
  {
    id: 58,
    title: "Gilded Age Heritage Townhouse",
    type: "House",
    price: "0.027",
    image: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=800&q=80",
    owner: "Boston Beacon Trust",
    location: "Boston, Massachusetts",
    specs: "4,600 sqft / Restored Brick / Lift",
    description: "A spectacular, landmark historic townhouse in Beacon Hill. Dual-occupancy rental yields are secured by long-term executive residency contracts.",
    yieldApr: 7.3,
    isDefault: true
  },
  {
    id: 59,
    title: "Renaissance Marble Masterpiece",
    type: "Other",
    price: "0.018",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    owner: "Florence Art Vault",
    location: "Florence, Italy",
    specs: "Carrara Marble / 16th Century / Certified",
    description: "An authentic, professionally conserved marble bust from late 16th-century Italy. Produces regular display dividends from museums and gallery leases worldwide.",
    yieldApr: 6.7,
    isDefault: true
  },
  {
    id: 60,
    title: "Zephyr All-Electric Aero-Cruiser",
    type: "Car",
    price: "0.020",
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    owner: "San Diego Yacht Basin",
    location: "San Diego, California",
    specs: "Solid-State Battery / Electric Quad-Drive",
    description: "A futuristic electric luxury aero-cruiser. Backed by elite charter booking pools and high-tier promo contracts under full commercial brokerage supervision.",
    yieldApr: 8.6,
    isDefault: true
  }
];

export const imagePresets = [
  {
    url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    label: "Luxury Villa",
    category: "House"
  },
  {
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    label: "Modern Penthouse",
    category: "House"
  },
  {
    url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    label: "Sleek Sportscar",
    category: "Car"
  },
  {
    url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    label: "Overland SUV",
    category: "Car"
  },
  {
    url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    label: "Mountain Chalet",
    category: "House"
  },
  {
    url: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=800&q=80",
    label: "Superyacht share",
    category: "Other"
  }
];
